name: update-movies-curl-test

on:
  schedule:
    - cron: '*/5 * * * *'
        
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: curl http://github-actions-test.jvnsgh2u35.ap-northeast-2.elasticbeanstalk.com/update-db/
